export const artists: { id: number; name: string }[] = [
  { id: 1, name: "Karol G" },
  { id: 2, name: "Blackpink" },
  { id: 3, name: "Bad Bunny" },
  { id: 4, name: "Shakira" },
  { id: 5, name: "BTS" },
  { id: 6, name: "The Weeknd" },
  { id: 7, name: "Taylor Swift" },
  { id: 8, name: "Anuel AA" },
  { id: 9, name: "Bizarrap" },
  { id: 10, name: "Grupo Frontera" },
  { id: 11, name: "Feid" },
  { id: 12, name: "Fuerza Regida" },
  { id: 13, name: "Eminem" },
  { id: 14, name: "Peso Pluma" },
  { id: 15, name: "Gusttavo Lima" },
  { id: 16, name: "Henrique e Juliano" },
  { id: 17, name: "Romeo Santos" },
  { id: 18, name: "Ed Sheeran" },
  { id: 19, name: "Sidhu Moose Wala" },
  { id: 20, name: "Marília Mendonça" },
];
